Repository MobileApps-Cascadia/orca-stars-android, pull requests merged in 2019-11, with the labels that each got.

#18 Digital prototype: https://marvelapp.com/project/4505681/
  Assets/Icons/ic_help_black_48dp.png
  Assets/Icons/ic_map_black_48dp.png
  Assets/Icons/ic_more_vert_black_48dp.png
  Assets/Icons/ic_star_border_black_48dp.png
  Assets/Images/797791.jpg
  Assets/Images/andres-iga-7XKkJVw1d8c-unsplash.jpg
  Assets/Images/photo-1462759353907-b2ea5ebd72e7.jpg
  Assets/Images/sketch-1573260595891.png
Labels: enhancement, user testing

#17 Added unapproved product backlog
  .idea/codeStyles/Project.xml
  .idea/misc.xml
  .idea/runConfigurations.xml
  Product Backlog.pdf
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: documentation

#36 Charles recview (recycler view)
  RecRest/.gitignore
  RecRest/.idea/.name
  RecRest/.idea/codeStyles/Project.xml
  RecRest/.idea/gradle.xml
  RecRest/.idea/misc.xml
  RecRest/.idea/runConfigurations.xml
  RecRest/app/.gitignore
  RecRest/app/build.gradle
  RecRest/app/proguard-rules.pro
  RecRest/app/src/androidTest/java/com/example/recrest/ExampleInstrumentedTest.java
  RecRest/app/src/main/AndroidManifest.xml
  RecRest/app/src/main/java/com/example/recrest/BusinessListAdapter.java
  RecRest/app/src/main/java/com/example/recrest/MainActivity.java
  RecRest/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  RecRest/app/src/main/res/drawable/ic_launcher_background.xml
  RecRest/app/src/main/res/layout/activity_main.xml
  RecRest/app/src/main/res/layout/activity_main_recyclerview.xml
  RecRest/app/src/main/res/layout/business_list_item.xml
  RecRest/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  RecRest/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  RecRest/app/src/main/res/mipmap-hdpi/ic_launcher.png
  RecRest/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  RecRest/app/src/main/res/mipmap-mdpi/ic_launcher.png
  RecRest/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  RecRest/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  RecRest/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  RecRest/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  RecRest/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  RecRest/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  RecRest/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  RecRest/app/src/main/res/values/colors.xml
  RecRest/app/src/main/res/values/strings.xml
  RecRest/app/src/main/res/values/styles.xml
  RecRest/app/src/test/java/com/example/recrest/ExampleUnitTest.java
  RecRest/build.gradle
  RecRest/gradle.properties
  RecRest/gradle/wrapper/gradle-wrapper.jar
  RecRest/gradle/wrapper/gradle-wrapper.properties
  RecRest/gradlew
  RecRest/gradlew.bat
  RecRest/settings.gradle
Labels: enhancement
